from pathlib import Path
import sys
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
from common import *


fig,axs=canvas(1,4,height=3,width=12);checks=[]
for ax,p in zip(axs.ravel(),[1,2,3,4]):
    phi,psi,z=pywt.Wavelet(f'db{p}').wavefun(level=10);curve(ax,z,psi,rf'$p={p}$ vanishing moments',r'$t$',r'$\psi(t)$');h=np.array(pywt.Wavelet(f'db{p}').rec_lo);k=np.arange(len(h));moments=[float(abs(np.sum((-1.)**k*k**r*h))) for r in range(p)];checks.append(moments);assert max(moments)<1e-9
finish(fig,__file__,'The mother wavelets are generated by the Daubechies cascade for p=1,2,3,4. Support length grows as 2p-1. Alternating moments of the scaling filter, which characterize the zero at the Nyquist frequency, are checked through order p-1. Overall wavelet sign follows the library’s documented filter convention.',parameters={'families':['db1','db2','db3','db4'],'cascade_level':10},checks={'nyquist_zero_moment_residuals':checks})
