function fig = fig()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.

load fig

h0 = figure('Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'PointerShapeCData',mat1, ...
	'Position',[520 720 560 420]);
h1 = axes('Parent',h0, ...
	'Box','on', ...
	'CameraUpVector',[0 1 0], ...
	'Color',[1 1 1], ...
	'ColorOrder',mat2, ...
	'XColor',[0 0 0], ...
	'YColor',[0 0 0], ...
	'ZColor',[0 0 0]);
h2 = line('Parent',h1, ...
	'Color',[0 0 1], ...
	'XData',mat3, ...
	'YData',mat4);
h2 = line('Parent',h1, ...
	'Color',[0 0.5 0], ...
	'XData',mat5, ...
	'YData',mat6);
h2 = line('Parent',h1, ...
	'Color',[1 0 0], ...
	'XData',mat7, ...
	'YData',mat8);
h2 = line('Parent',h1, ...
	'Color',[0 0.75 0.75], ...
	'XData',mat9, ...
	'YData',mat10);
h2 = line('Parent',h1, ...
	'Color',[0.75 0 0.75], ...
	'XData',mat11, ...
	'YData',mat12);
h2 = line('Parent',h1, ...
	'Color',[0.75 0.75 0], ...
	'XData',mat13, ...
	'YData',mat14);
h2 = line('Parent',h1, ...
	'Color',[0.25 0.25 0.25], ...
	'XData',mat15, ...
	'YData',mat16);
if nargout > 0, fig = h0; end
