"""Build editable figure reconstructions and their chapter review pages."""
from concurrent.futures import ThreadPoolExecutor
import json
from pathlib import Path
import re
import shutil
import unicodedata


def entries(root):
    result = []
    for manifest in sorted((root / "figures/tikz").glob("*.json")):
        result.extend(json.loads(manifest.read_text()))
    ids = [entry["id"] for entry in result]
    if len(ids) != len(set(ids)):
        raise RuntimeError("Duplicate figure review identifiers")
    for entry in result:
        for field in ("id", "chapter", "original", "tex", "title", "context", "notes", "confidence"):
            if field not in entry:
                raise RuntimeError(f"Missing {field} in figure review {entry}")
        for path in (root / "figures" / entry["original"], root / entry["tex"]):
            if not path.is_file():
                raise RuntimeError(f"Missing figure review source: {path}")
    return result


def tex_text(value):
    replacements = {"&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#",
                    "_": r"\_", "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}",
                    "^": r"\textasciicircum{}", "\\": r"\textbackslash{}",
                    "–": "--", "—": "---", "’": "'", "‘": "`", "“": "``", "”": "''",
                    "≤": r"\ensuremath{\leq}", "≥": r"\ensuremath{\geq}",
                    "±": r"\ensuremath{\pm}", "×": r"\ensuremath{\times}",
                    "→": r"\ensuremath{\to}", "∞": r"\ensuremath{\infty}",
                    "∈": r"\ensuremath{\in}", "∥": r"\ensuremath{\Vert}",
                    "〈": r"\ensuremath{\langle}", "〉": r"\ensuremath{\rangle}", "−": "-",
                    "₁": r"\textsubscript{1}", "₂": r"\textsubscript{2}",
                    "²": r"\textsuperscript{2}", "³": r"\textsuperscript{3}"}
    for char, command in zip("αβγδεθλμνπρστφωΣΦΩ", (
            "alpha beta gamma delta epsilon theta lambda mu nu pi rho sigma tau phi omega Sigma Phi Omega").split()):
        replacements[char] = "\\ensuremath{\\" + command + "}"
    return "".join(replacements.get(char, char) for char in unicodedata.normalize("NFC", value))


def context_text(value):
    """Render book-label tokens as numbered, clickable mathematical references."""
    pattern = r"\b(?:eq|fig|prop|thm|sec|lem)-[A-Za-z0-9_:-]+"
    parts = re.split("(" + pattern + ")", value)
    return "".join((r"\eqref{" if part.startswith("eq-") else r"\ref{") + part + "}"
                   if re.fullmatch(pattern, part) else tex_text(part) for part in parts)


def build_reviews(root, build, chapters, run, diagnostic, jobs=4):
    figures = entries(root)
    directory = build / "tikz-figures"
    directory.mkdir(parents=True, exist_ok=True)
    preamble = root / "figures/tikz/tikz-preamble.tex"

    def compile_figure(entry):
        source = root / entry["tex"]
        destination = source.with_suffix(".pdf")
        if destination.exists() and destination.stat().st_mtime >= max(source.stat().st_mtime, preamble.stat().st_mtime):
            return
        run(["pdflatex", "-interaction=nonstopmode", "-halt-on-error", "-file-line-error",
             f"-output-directory={directory.relative_to(root)}", str(source)], directory / f"{source.stem}.txt")
        log = (directory / f"{source.stem}.log").read_text(errors="replace")
        problems = [line for line in log.splitlines() if diagnostic.match(line)]
        if problems:
            raise RuntimeError(f"Figure diagnostics in {source.name}:\n" + "\n".join(problems))
        shutil.copy2(directory / destination.name, destination)

    sources = {entry["tex"]: entry for entry in figures}
    with ThreadPoolExecutor(max_workers=max(1, jobs)) as pool:
        list(pool.map(compile_figure, sources.values()))

    review_dir = root / "figures/tikz/reviews"
    review_dir.mkdir(exist_ok=True)
    for chapter in chapters:
        selected = [entry for entry in figures if entry["chapter"] == chapter]
        lines = ["% Generated by scripts/tikz_reviews.py from the figure manifests."]
        for entry in selected:
            args = [tex_text(entry["title"]), "figures/" + entry["original"],
                    str(Path(entry["tex"]).with_suffix(".pdf")), context_text(entry["context"]),
                    tex_text(("Interpretation to check: " if entry["confidence"] == "qualified" else "") + entry["notes"]), entry["id"]]
            lines.append("\\ReviewFigure" + "\n".join("{" + arg + "}" for arg in args))
        target = review_dir / f"{chapter}.tex"
        if selected:
            target.write_text("\n".join(lines) + "\n")
        elif target.exists():
            target.unlink()
    unknown = {entry["chapter"] for entry in figures} - set(chapters)
    if unknown:
        raise RuntimeError(f"Unknown figure-review chapters: {unknown}")
    print(f"Prepared {len(figures)} original/TikZ comparisons.", flush=True)
