names = {...
    'picasso', ...
    'bleu-2', ...
    'cezanne', ...
    'multi-1', ...
    'multi-2', ...
    'multi-4', ...
    'multi-5', ...
    'rouge-1', ...
    'rouge-3', ...
    };


for in=1:length(names)
    name = names{in};
    ColorClouds;
end